import type { Client, Industry } from "@prisma/client";

export const getPojectsData = (clients: Client[], industries: Industry[]) => [
	{
		name: "Pinnacle",
		clientId: clients[0].id,
		industryId: industries[3].id,
	},
	{
		name: "Aurora",
		clientId: clients[1].id,
		industryId: industries[1].id,
	},
	{
		name: "Nova Management System",
		clientId: clients[2].id,
		industryId: industries[2].id,
	},
	{
		name: "ERP Zephyr",
		clientId: clients[3].id,
		industryId: industries[0].id,
	},
	{
		name: "IMP Summit",
		clientId: clients[4].id,
		industryId: industries[3].id,
	},
	{
		name: "Orion Automation Tool",
		clientId: clients[5].id,
		industryId: industries[9].id,
	},
	{
		name: "Momentum - Cloud Infrastructure",
		clientId: clients[6].id,
		industryId: industries[0].id,
	},
	{
		name: "Catalyst iOS",
		clientId: clients[7].id,
		industryId: industries[0].id,
	},
	{
		name: "Nebula Pipeline",
		clientId: clients[8].id,
		industryId: industries[0].id,
	},
	{
		name: "Startup Falcon",
		clientId: clients[9].id,
		industryId: industries[0].id,
	},
	{ name: "Pinnacle", clientId: clients[0].id, industryId: industries[3].id },
	{ name: "Aurora", clientId: clients[1].id, industryId: industries[1].id },
	{
		name: "Nova Management System",
		clientId: clients[2].id,
		industryId: industries[2].id,
	},
	{ name: "ERP Zephyr", clientId: clients[3].id, industryId: industries[0].id },
	{ name: "IMP Summit", clientId: clients[4].id, industryId: industries[3].id },
	{ name: "Atlas CRM", clientId: clients[5].id, industryId: industries[5].id },
	{
		name: "Eclipse Analytics",
		clientId: clients[6].id,
		industryId: industries[6].id,
	},
	{ name: "Vantage AI", clientId: clients[7].id, industryId: industries[4].id },
	{
		name: "Nexus Cloud",
		clientId: clients[8].id,
		industryId: industries[2].id,
	},
	{ name: "Vertex Hub", clientId: clients[9].id, industryId: industries[7].id },
	{
		name: "Stratos ERP",
		clientId: clients[10].id,
		industryId: industries[0].id,
	},
	{
		name: "Quantum Insight",
		clientId: clients[11].id,
		industryId: industries[8].id,
	},
	{
		name: "Orion Portal",
		clientId: clients[12].id,
		industryId: industries[1].id,
	},
	{
		name: "Helix Workforce",
		clientId: clients[13].id,
		industryId: industries[5].id,
	},
	{
		name: "Nimbus Tracker",
		clientId: clients[14].id,
		industryId: industries[3].id,
	},
	{
		name: "Polaris Connect",
		clientId: clients[15].id,
		industryId: industries[6].id,
	},
	{
		name: "Aether Pay",
		clientId: clients[16].id,
		industryId: industries[4].id,
	},
	{ name: "Lumen OS", clientId: clients[17].id, industryId: industries[9].id },
	{
		name: "Ignite Platform",
		clientId: clients[18].id,
		industryId: industries[1].id,
	},
	{
		name: "Horizon Data Hub",
		clientId: clients[19].id,
		industryId: industries[2].id,
	},
	{ name: "Pulse CRM", clientId: clients[20].id, industryId: industries[0].id },
	{
		name: "Elevate ERP",
		clientId: clients[21].id,
		industryId: industries[5].id,
	},
	{
		name: "Catalyst Engine",
		clientId: clients[22].id,
		industryId: industries[3].id,
	},
	{
		name: "Spectra Analytics",
		clientId: clients[23].id,
		industryId: industries[4].id,
	},
	{
		name: "Flux AI Assistant",
		clientId: clients[24].id,
		industryId: industries[6].id,
	},
	{ name: "Pulse360", clientId: clients[25].id, industryId: industries[8].id },
	{
		name: "Haven Portal",
		clientId: clients[26].id,
		industryId: industries[9].id,
	},
	{ name: "AstraHub", clientId: clients[27].id, industryId: industries[2].id },
	{
		name: "Momentum Manager",
		clientId: clients[28].id,
		industryId: industries[3].id,
	},
	{
		name: "CloudStride",
		clientId: clients[29].id,
		industryId: industries[0].id,
	},
	{
		name: "Synergy Pay",
		clientId: clients[30].id,
		industryId: industries[4].id,
	},
	{ name: "OmniDesk", clientId: clients[31].id, industryId: industries[6].id },
	{
		name: "Vertex Flow",
		clientId: clients[32].id,
		industryId: industries[7].id,
	},
	{
		name: "Lattice Insights",
		clientId: clients[33].id,
		industryId: industries[5].id,
	},
	{
		name: "Comet Suite",
		clientId: clients[34].id,
		industryId: industries[3].id,
	},
	{
		name: "Apollo CRM",
		clientId: clients[35].id,
		industryId: industries[8].id,
	},
	{ name: "Zephyr HR", clientId: clients[36].id, industryId: industries[1].id },
	{
		name: "Nucleus Portal",
		clientId: clients[37].id,
		industryId: industries[0].id,
	},
	{
		name: "Solaris AI",
		clientId: clients[38].id,
		industryId: industries[9].id,
	},
	{
		name: "Trinity Data",
		clientId: clients[39].id,
		industryId: industries[4].id,
	},
	{
		name: "Echo Cloud",
		clientId: clients[40].id,
		industryId: industries[3].id,
	},
	{
		name: "Vector Hub",
		clientId: clients[41].id,
		industryId: industries[6].id,
	},
	{ name: "Nimbus HR", clientId: clients[42].id, industryId: industries[2].id },
	{
		name: "Prism Manager",
		clientId: clients[43].id,
		industryId: industries[5].id,
	},
	{ name: "CoreLink", clientId: clients[44].id, industryId: industries[7].id },
	{ name: "Omnia ERP", clientId: clients[45].id, industryId: industries[8].id },
	{
		name: "Skyline Pay",
		clientId: clients[46].id,
		industryId: industries[1].id,
	},
	{
		name: "Zenith Portal",
		clientId: clients[47].id,
		industryId: industries[4].id,
	},
	{ name: "Lyra CRM", clientId: clients[48].id, industryId: industries[9].id },
	{
		name: "Arcadia Suite",
		clientId: clients[49].id,
		industryId: industries[5].id,
	},
	{
		name: "Cobalt Tracker",
		clientId: clients[50].id,
		industryId: industries[6].id,
	},
	{
		name: "Elevon Manager",
		clientId: clients[51].id,
		industryId: industries[3].id,
	},
	{ name: "Strive AI", clientId: clients[52].id, industryId: industries[8].id },
	{ name: "PulseEdge", clientId: clients[53].id, industryId: industries[2].id },
	{ name: "EchoPay", clientId: clients[54].id, industryId: industries[1].id },
	{
		name: "SpectraLink",
		clientId: clients[55].id,
		industryId: industries[4].id,
	},
	{ name: "VertexIQ", clientId: clients[56].id, industryId: industries[9].id },
	{ name: "DataForge", clientId: clients[57].id, industryId: industries[0].id },
	{
		name: "Aurion Cloud",
		clientId: clients[58].id,
		industryId: industries[2].id,
	},
	{
		name: "Lumina Portal",
		clientId: clients[59].id,
		industryId: industries[5].id,
	},
	{ name: "Helix360", clientId: clients[60].id, industryId: industries[4].id },
	{ name: "Optima AI", clientId: clients[61].id, industryId: industries[6].id },
	{
		name: "Sierra ERP",
		clientId: clients[62].id,
		industryId: industries[3].id,
	},
	{ name: "NovaFlow", clientId: clients[63].id, industryId: industries[9].id },
	{ name: "CloudBeam", clientId: clients[64].id, industryId: industries[8].id },
	{ name: "Omni360", clientId: clients[65].id, industryId: industries[7].id },
	{
		name: "PulseWorks",
		clientId: clients[66].id,
		industryId: industries[0].id,
	},
	{
		name: "SpectraCore",
		clientId: clients[67].id,
		industryId: industries[2].id,
	},
	{
		name: "QuantumEdge",
		clientId: clients[68].id,
		industryId: industries[1].id,
	},
	{
		name: "NimbusDesk",
		clientId: clients[69].id,
		industryId: industries[4].id,
	},
	{ name: "LyraAI", clientId: clients[70].id, industryId: industries[6].id },
	{
		name: "AuroraNext",
		clientId: clients[71].id,
		industryId: industries[5].id,
	},
	{ name: "FusionCRM", clientId: clients[72].id, industryId: industries[3].id },
	{ name: "CorePay", clientId: clients[73].id, industryId: industries[0].id },
	{ name: "HelixLink", clientId: clients[74].id, industryId: industries[9].id },
	{ name: "PrismEdge", clientId: clients[75].id, industryId: industries[4].id },
	{ name: "OrionOne", clientId: clients[76].id, industryId: industries[2].id },
	{
		name: "ZephyrWorks",
		clientId: clients[77].id,
		industryId: industries[6].id,
	},
	{ name: "VertexPro", clientId: clients[78].id, industryId: industries[8].id },
	{ name: "OmniaData", clientId: clients[79].id, industryId: industries[5].id },
	{
		name: "PinnacleFlow",
		clientId: clients[80].id,
		industryId: industries[3].id,
	},
	{ name: "SkySync", clientId: clients[81].id, industryId: industries[9].id },
	{ name: "LumenCore", clientId: clients[82].id, industryId: industries[0].id },
	{
		name: "StratosEdge",
		clientId: clients[83].id,
		industryId: industries[7].id,
	},
	{ name: "EchoSuite", clientId: clients[84].id, industryId: industries[4].id },
	{ name: "VantageOS", clientId: clients[85].id, industryId: industries[1].id },
	{
		name: "MomentumAI",
		clientId: clients[86].id,
		industryId: industries[8].id,
	},
	{ name: "SolarEdge", clientId: clients[87].id, industryId: industries[9].id },
	{ name: "NimbusOne", clientId: clients[88].id, industryId: industries[2].id },
	{ name: "OrionIQ", clientId: clients[89].id, industryId: industries[3].id },
	{
		name: "AetherCloud",
		clientId: clients[90].id,
		industryId: industries[5].id,
	},
	{
		name: "ZenithSuite",
		clientId: clients[91].id,
		industryId: industries[7].id,
	},
	{ name: "PulseLink", clientId: clients[92].id, industryId: industries[4].id },
	{ name: "NovaEdge", clientId: clients[93].id, industryId: industries[6].id },
	{ name: "CoreSync", clientId: clients[94].id, industryId: industries[0].id },
	{ name: "OmniAI", clientId: clients[95].id, industryId: industries[8].id },
	{ name: "VortexHub", clientId: clients[96].id, industryId: industries[1].id },
	{
		name: "EclipseOne",
		clientId: clients[97].id,
		industryId: industries[9].id,
	},
	{ name: "AstraLink", clientId: clients[98].id, industryId: industries[2].id },
	{ name: "HelixFlow", clientId: clients[99].id, industryId: industries[4].id },
];
