import type { Client, Project, TimeLogCategory, User } from "@prisma/client";

export const getMyTimeLogs = (
	user: User,
	clients: Client[],
	projects: Project[],
	categories: TimeLogCategory[],
) => [
	{
		date: new Date("2025-10-01"),
		hours: 8,
		description: "Updated core module",
		userId: user.id,
		clientId: clients[0].id,
		projectId: projects[0].id,
		categoryId: categories[3].id,
	},
	{
		date: new Date("2025-10-02"),
		hours: 6,
		description: "Refactored old API",
		userId: user.id,
		clientId: clients[1].id,
		projectId: projects[1].id,
		categoryId: categories[5].id,
	},
	{
		date: new Date("2025-10-03"),
		hours: 5,
		description: "Team sync meeting",
		userId: user.id,
		clientId: clients[2].id,
		projectId: projects[2].id,
		categoryId: categories[2].id,
	},

	{
		date: new Date("2025-10-06"),
		hours: 7,
		description: "Improved UX layout",
		userId: user.id,
		clientId: clients[3].id,
		projectId: projects[3].id,
		categoryId: categories[1].id,
	},
	{
		date: new Date("2025-10-07"),
		hours: 8,
		description: "Working on design system",
		userId: user.id,
		clientId: clients[4].id,
		projectId: projects[4].id,
		categoryId: categories[7].id,
	},
	{
		date: new Date("2025-11-07"),
		hours: 1,
		description: "Development",
		userId: user.id,
		clientId: clients[3].id,
		projectId: projects[3].id,
		categoryId: categories[7].id,
	},
	{
		date: new Date("2025-10-08"),
		hours: 9,
		description: "Major feature deployment",
		userId: user.id,
		clientId: clients[5].id,
		projectId: projects[5].id,
		categoryId: categories[0].id,
	}, // 9h #1
	{
		date: new Date("2025-10-09"),
		hours: 4,
		description: "Bug fixes",
		userId: user.id,
		clientId: clients[6].id,
		projectId: projects[6].id,
		categoryId: categories[9].id,
	},
	{
		date: new Date("2025-10-10"),
		hours: 7,
		description: "Optimized queries",
		userId: user.id,
		clientId: clients[7].id,
		projectId: projects[7].id,
		categoryId: categories[4].id,
	},

	{
		date: new Date("2025-10-13"),
		hours: 6,
		description: "Documentation updates",
		userId: user.id,
		clientId: clients[8].id,
		projectId: projects[8].id,
		categoryId: categories[3].id,
	},
	{
		date: new Date("2025-10-14"),
		hours: 8,
		description: "Styled components rewrite",
		userId: user.id,
		clientId: clients[9].id,
		projectId: projects[9].id,
		categoryId: categories[8].id,
	},
	{
		date: new Date("2025-10-15"),
		hours: 3,
		description: "Minor layout tweaks",
		userId: user.id,
		clientId: clients[10].id,
		projectId: projects[10].id,
		categoryId: categories[6].id,
	},
	{
		date: new Date("2025-10-16"),
		hours: 9,
		description: "API performance improvements",
		userId: user.id,
		clientId: clients[11].id,
		projectId: projects[11].id,
		categoryId: categories[0].id,
	}, // 9h #2
	{
		date: new Date("2025-10-17"),
		hours: 7,
		description: "Refactoring auth logic",
		userId: user.id,
		clientId: clients[12].id,
		projectId: projects[12].id,
		categoryId: categories[5].id,
	},

	{
		date: new Date("2025-10-20"),
		hours: 8,
		description: "Frontend polish",
		userId: user.id,
		clientId: clients[13].id,
		projectId: projects[13].id,
		categoryId: categories[2].id,
	},
	{
		date: new Date("2025-10-21"),
		hours: 6,
		description: "Backend cleanup",
		userId: user.id,
		clientId: clients[14].id,
		projectId: projects[14].id,
		categoryId: categories[4].id,
	},
	{
		date: new Date("2025-10-22"),
		hours: 5,
		description: "Added tooltips",
		userId: user.id,
		clientId: clients[15].id,
		projectId: projects[15].id,
		categoryId: categories[9].id,
	},
	{
		date: new Date("2025-10-23"),
		hours: 8,
		description: "Test suite maintenance",
		userId: user.id,
		clientId: clients[16].id,
		projectId: projects[16].id,
		categoryId: categories[7].id,
	},
	{
		date: new Date("2025-10-24"),
		hours: 4,
		description: "Mock data updates",
		userId: user.id,
		clientId: clients[17].id,
		projectId: projects[17].id,
		categoryId: categories[3].id,
	},

	{
		date: new Date("2025-10-27"),
		hours: 7,
		description: "Cleanup unused code",
		userId: user.id,
		clientId: clients[18].id,
		projectId: projects[18].id,
		categoryId: categories[2].id,
	},
	{
		date: new Date("2025-10-28"),
		hours: 8,
		description: "Improved validation",
		userId: user.id,
		clientId: clients[19].id,
		projectId: projects[19].id,
		categoryId: categories[8].id,
	},
	{
		date: new Date("2025-10-29"),
		hours: 2,
		description: "Quick fixes",
		userId: user.id,
		clientId: clients[20].id,
		projectId: projects[20].id,
		categoryId: categories[4].id,
	},
	{
		date: new Date("2025-10-30"),
		hours: 9,
		description: "Large feature push",
		userId: user.id,
		clientId: clients[21].id,
		projectId: projects[21].id,
		categoryId: categories[1].id,
	}, // 9h #3
	{
		date: new Date("2025-10-31"),
		hours: 5,
		description: "Sprint planning",
		userId: user.id,
		clientId: clients[22].id,
		projectId: projects[22].id,
		categoryId: categories[6].id,
	},

	{
		date: new Date("2025-11-03"),
		hours: 7,
		description: "Improved caching system",
		userId: user.id,
		clientId: clients[0].id,
		projectId: projects[0].id,
		categoryId: categories[9].id,
	},
	{
		date: new Date("2025-11-04"),
		hours: 6,
		description: "Meeting with product team",
		userId: user.id,
		clientId: clients[1].id,
		projectId: projects[1].id,
		categoryId: categories[8].id,
	},
	{
		date: new Date("2025-11-05"),
		hours: 4,
		description: "UI minor fixes",
		userId: user.id,
		clientId: clients[2].id,
		projectId: projects[2].id,
		categoryId: categories[7].id,
	},
	{
		date: new Date("2025-11-06"),
		hours: 8,
		description: "Database tuning",
		userId: user.id,
		clientId: clients[3].id,
		projectId: projects[3].id,
		categoryId: categories[4].id,
	},
	{
		date: new Date("2025-11-07"),
		hours: 3,
		description: "Hotfix deployment",
		userId: user.id,
		clientId: clients[4].id,
		projectId: projects[4].id,
		categoryId: categories[0].id,
	},

	{
		date: new Date("2025-11-10"),
		hours: 7,
		description: "API endpoint improvements",
		userId: user.id,
		clientId: clients[5].id,
		projectId: projects[5].id,
		categoryId: categories[5].id,
	},
	{
		date: new Date("2025-11-11"),
		hours: 8,
		description: "Modularized helpers",
		userId: user.id,
		clientId: clients[6].id,
		projectId: projects[6].id,
		categoryId: categories[3].id,
	},
	{
		date: new Date("2025-11-12"),
		hours: 9,
		description: "Large architecture refactor",
		userId: user.id,
		clientId: clients[7].id,
		projectId: projects[7].id,
		categoryId: categories[1].id,
	}, // 9h #4
	{
		date: new Date("2025-11-13"),
		hours: 5,
		description: "Finished ticket updates",
		userId: user.id,
		clientId: clients[8].id,
		projectId: projects[8].id,
		categoryId: categories[6].id,
	},
	{
		date: new Date("2025-11-14"),
		hours: 7,
		description: "Internal cleanup tasks",
		userId: user.id,
		clientId: clients[9].id,
		projectId: projects[9].id,
		categoryId: categories[2].id,
	},

	{
		date: new Date("2025-12-01"),
		hours: 8,
		description: "Refined error handling",
		userId: user.id,
		clientId: clients[10].id,
		projectId: projects[10].id,
		categoryId: categories[4].id,
	},
	{
		date: new Date("2025-12-02"),
		hours: 6,
		description: "Added reusable hooks",
		userId: user.id,
		clientId: clients[11].id,
		projectId: projects[11].id,
		categoryId: categories[7].id,
	},
	{
		date: new Date("2025-12-03"),
		hours: 4,
		description: "Fixed small regressions",
		userId: user.id,
		clientId: clients[12].id,
		projectId: projects[12].id,
		categoryId: categories[8].id,
	},
	{
		date: new Date("2025-12-04"),
		hours: 7,
		description: "Improved test coverage",
		userId: user.id,
		clientId: clients[13].id,
		projectId: projects[13].id,
		categoryId: categories[9].id,
	},
	{
		date: new Date("2025-12-05"),
		hours: 5,
		description: "CI adjustments",
		userId: user.id,
		clientId: clients[14].id,
		projectId: projects[14].id,
		categoryId: categories[3].id,
	},

	{
		date: new Date("2025-12-08"),
		hours: 8,
		description: "Final Q4 tasks",
		userId: user.id,
		clientId: clients[15].id,
		projectId: projects[15].id,
		categoryId: categories[0].id,
	},
	{
		date: new Date("2025-12-09"),
		hours: 3,
		description: "Reviewing PRs",
		userId: user.id,
		clientId: clients[16].id,
		projectId: projects[16].id,
		categoryId: categories[1].id,
	},
	{
		date: new Date("2025-12-10"),
		hours: 6,
		description: "Dashboard refinements",
		userId: user.id,
		clientId: clients[17].id,
		projectId: projects[17].id,
		categoryId: categories[2].id,
	},
	{
		date: new Date("2025-12-11"),
		hours: 8,
		description: "Improved UI state handling",
		userId: user.id,
		clientId: clients[18].id,
		projectId: projects[18].id,
		categoryId: categories[4].id,
	},
	{
		date: new Date("2025-12-12"),
		hours: 4,
		description: "Small fixes",
		userId: user.id,
		clientId: clients[19].id,
		projectId: projects[19].id,
		categoryId: categories[5].id,
	},
];
